config/routes.rb
AppLift::Application.routes.draw do
  resources :gadgets

  root 'gadgets#index'
end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  belongs_to :user

  validates :name, :description, :user_id, presence: true
  validates :name, length: { maximum: 255 }
  validates :description, length: { maximum: 10000 }

  scope :with_user_if_present, ->(user_id)          { where(user_id: user_id) if user_id.present? }

  has_attached_file :image,
                    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment :image, presence: true,
                       content_type: { content_type: ['image/png', 'image/gif', 'image/jpg', 'image/jpeg'] },
                       size: { in: 0..2.megabytes }

  def tags=(values)
    write_attribute(:tags, (values.is_a?(Array) ? values : values.split(',')).map(&:strip) )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :gadgets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, except: [:index, :show]

  def index
    @gadgets = Gadget.with_user_if_present(params[:my] ? current_user.try(:id) : nil).page(params[:page])
  end

  def show
  end

  def new
    @gadget = current_user.gadgets.build
  end

  def create
    @gadget = current_user.gadgets.build(gadget_params)

    if @gadget.save
      redirect_to @gadget, flash: { success: 'Gadget was successfully created.' }
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @gadget.update(gadget_params)
      redirect_to @gadget, flash: { success: 'User was successfully updated.' }
    else
      render action: 'edit'
    end
  end

  private

  def set_user
    @gadget = Gadget.find(params[:id])
  end

  def gadget_params
    params.require(:gadget).permit(:name, :description, :image, :tags)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  private

  def user_from_params
    User.new(params[:user] ? permit_params : Hash.new)
  end

  def permit_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gadgets/_form.html.erb
<%= form_for @gadget, html: { class: 'form-horizontal', multipart: true } do |f| %>

  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tags, class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :tags, class: 'form-control', value: @gadget.tags.join(', ') %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image, class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/gadgets/edit.html.erb
<div class="page-header clearfix">
  <h3 class='pull-left'>Editing Gadget</h3>
  <%= link_to 'Back', gadgets_path, class: 'btn btn-link pull-right' %>
</div>

<%= render 'form' %>

app/views/gadgets/index.html.erb
<div class="page-header clearfix">
  <h3 class='pull-left'>Gadgets</h3>
  <%= link_to 'Create', new_gadget_path, class: 'btn btn-primary pull-right' if signed_in? %>
</div>


<div class="row" id="gadgets">
  <% @gadgets.each_with_index do |gadget, index| %>
    <div class="col-sm-6 col-md-4 item">
      <div class="thumbnail">
        <%= link_to gadget do %>
          <%= image_tag gadget.image.url(:thumb) %>
        <% end %>
        <div class="caption">
          <h3>
            <%= link_to gadget.name, gadget %>
          </h3>
          <p class="tags">
            <%= gadget.tags.join(', ') %>
          </p>

          <hr>

          <p>
            <%= link_to 'Details', gadget, class: 'btn btn-primary' %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= paginate @gadgets %>

app/views/gadgets/new.html.erb
<div class="page-header clearfix">
  <h3 class='pull-left'>New Gadget</h3>
  <%= link_to 'Back', gadgets_path, class: 'btn btn-link pull-right' %>
</div>

<%= render 'form' %>

app/views/gadgets/show.html.erb
<div class="page-header clearfix">
  <h3 class='pull-left'><%= @gadget.name %></h3>
  <%= link_to 'Back', gadgets_path, class: 'btn btn-link pull-right' %>
  <%= link_to 'Edit', edit_gadget_path(@gadget), class: 'btn btn-primary pull-right' if signed_in? %>
</div>



<dl class="dl-horizontal">

  <dt></dt>
  <dd><%= image_tag @gadget.image.url(:medium) %></dd>
  <dt><%= t('activerecord.attributes.gadget.tags') %>:</dt>
  <dd><%= @gadget.tags.join(', ') %></dd>
  <dt><%= t('activerecord.attributes.gadget.description') %>:</dt>
  <dd><%= simple_format @gadget.description %></dd>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= display_meta_tags site: t('site_name') %>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('site_name'), root_url, class: 'navbar-brand' %>
    </div>
    <%= render 'shared/head_nav' %>
  </div>
</nav>

<div class="container">
  <%= render 'shared/flash' %>
  <%= yield %>
  <hr>

  <footer>
    <p></p>
  </footer>
</div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-block alert-error">
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %>.</li>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/shared/_head_nav.html.erb
<div class="collapse navbar-collapse navbar-static-top" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to 'Gadgets', gadgets_path %></li>

    <% if signed_in? %>
      <li><%= link_to 'My Gadgets', gadgets_path(my: true) %></li>
      <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign In', sign_in_path %></li>
      <li><%= link_to 'Sign Up', sign_up_path %></li>
    <% end %>
  </ul>
</div>

app/views/users/_form.html.erb
<%= form_for @user, html: { class: 'form-horizontal', multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.text_field :email, type: :email, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: 'col-sm-2 control-label' %>
    <div class="col-sm-6">
      <%= f.password_field :password, class: 'form-control', required: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to t('.sign_in'), sign_up_path, class: 'btn btn-link' %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="page-header clearfix">
  <h3 class='pull-left'>New User</h3>
</div>

<%= render 'users/form' %>